CREATE TABLE IF NOT EXISTS stocks (
    id         SERIAL PRIMARY KEY,
    sku        VARCHAR(100) UNIQUE NOT NULL,
    quantity   INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);